global:
  scrape_interval:     30s
  evaluation_interval: 30s
  scrape_timeout:      5s

  external_labels:
    monitor: '{{ prometheus_host_label }}'

rule_files:
  - 'node.rules'

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets:
          - '127.0.0.1:9323'
        labels:
          host: '{{ prometheus_host_label }}'

  - job_name: 'node'
    static_configs:
      - targets:
          - '127.0.0.1:9100'
        labels:
          host: '{{ prometheus_host_label }}'
