#!/bin/bash
set -e

# TODO: Clean this up (build, container, test, etc)
CERTBOT_VERSION=v1.12.0

hosts=({{ virtual_host }}{{ ' ' if extra_tls_hosts else '' }}{{ extra_tls_hosts|join(' ') }})

for host in ${hosts[@]}; do
  docker run --rm                                 \
     -v /tls/letsencrypt:/etc/letsencrypt         \
     -v /var/www/html:/webroot                    \
     certbot/certbot:"$CERTBOT_VERSION" certonly  \
     --non-interactive                            \
     --agree-tos                                  \
     --email lucas@smartmousetravel.com           \
     --keep-until-expiring                        \
     --webroot                                    \
     --webroot-path /webroot                      \
     --domain ${host}
done
