#!/bin/bash
set -e

# TODO: Clean this up (build, container, test, etc)
CERTBOT_VERSION=v1.12.0

SOURCE_DIR=/etc/nginx/sites-available
DEST_DIR=/etc/nginx/sites-enabled

find "$SOURCE_DIR" -type f | while read f; do
    domain=$(grep '^#gencerts' "$f" | awk '{print $2}')
    if [ -z "$domain" ]; then
        continue
    fi
    docker run --rm                                     \
           -v /tls/letsencrypt:/etc/letsencrypt         \
           -v /var/www/html:/webroot                    \
           certbot/certbot:"$CERTBOT_VERSION" certonly  \
           --non-interactive                            \
           --agree-tos                                  \
           --email lucas@smartmousetravel.com           \
           --keep-until-expiring                        \
           --webroot                                    \
           --webroot-path /webroot                      \
           --domain "$domain"

    if ! [ -e "/tls/letsencrypt/live/${domain}/cert.pem" ]; then
        continue
    fi
    basef=$(basename "$f")
    if [ -e "$DEST_DIR"/"$basef" ]; then
        continue
    fi
    ln -s "$f" "$DEST_DIR"
done
