- name: Get Docker upstream APT GPG key
  apt_key:
    id: '{{ docker_apt_key }}'
    keyserver: 'hkp://pool.sks-keyservers.net'
    state: present

- name: Configure upstream APT repository
  apt_repository:
    repo: '{{ docker_repository }}'
    update_cache: True
    state: present

- name: Install Docker
  apt:
    pkg:
      - 'containerd.io'
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'docker-compose'
    update_cache: yes
    state: present

- name: Install Docker daemon config
  copy:
    src: 'docker-daemon.json'
    dest: '/etc/docker/daemon.json'

- name: Add specific users to docker group
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: True
  with_items: '{{ docker_users }}'
  when: docker_users|bool
